### ISSUE TITLE
Should enhance latency by display images asynchronously etc

### ISSUE THREAD

**Issue by promisivia** [ipads-multimedia-storage/flink-server#5]
Now the display of video which blocking the process time
More, we can try skip some frames to enhance the time too

**Comment by promisivia** [comment]
now the server can display images asynchronously #6 
- this feature improve process latency from 15ms to around 5ms
- testing environment: Windows PC, with it own camera
- still can choose to hide the video display

**Comment by HR-SU** [comment]
Nice job!
