### ISSUE TITLE
some times (Very rare) an JSONException occur when parse the JOSN passed from client

### ISSUE THREAD

**Issue by promisivia** [ipads-multimedia-storage/flink-server#7]
There is an Exception " org.json.JSONException: Expected a ',' or '}'" in flink.source.OpenCVSocketSource.
But it is very rare. Until now, it occurs only two times.
We guess it might be cause by the broken of JSON during network transmission whatever

**Comment by HR-SU** [comment]
We found there are two more whitespace characters at the beginning of the JSON string every time this error occurs, leading to incompleteness of the JSON string. After careful investigation, we still don't have any idea about how this could have happened. 
Maybe network transportation is what to blame?

**Comment by Gusabary** [comment]
solved,
key is that we reading the stream while stream receiving bytes at the same time, so it's possible to read less than 16 bytes in a single try
